spring:
  application:
    name: validation-service
  kafka:
    bootstrap-servers: 192.168.1.6:9092

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my-KafkaGroup
      auto-offset-reset: earliest
server:
  port: 9093